### ISSUE TITLE
Use attribute of weather sensor

### ISSUE THREAD

**Issue by fredrikbaberg** [timmo001/home-panel#197]
# Description

When using a weather sensor such as SMHI (https://www.home-assistant.io/components/smhi/, through integration), the state corresponds to the summary. To get the temperature and humidity, this has to be extracted, which is not possible directly from Home Panel.

## Suggested Actions

Enable the use of attributes, so that a specific attribute can be used instead of extracting the data through a template in Home Assistant.

## Additional

<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/components/smhi/">SMHI</a></strong></div><div>Instructions on how to integrate SMHI forecasts within Home Assistant.</div></blockquote>

**Comment by michaeldavie** [comment]
Interesting idea. To put this another way, I think what you're looking for is basically an `attribute` card, which would be based on an attribute of an entity instead of the state of one. As you point out, you could also use a [template sensor](https://www.home-assistant.io/components/template/) to turn an attribute into an entity directly in Home Assistant.

**Comment by timmo001** [comment]
To avoid fragmenting the app, template sensors should be used and the app should stay as is. It's a nice idea, but has a viable alternative which will store history in ha
