### ISSUE TITLE
Alarm Tile

### ISSUE THREAD

**Issue by TheCellMC** [timmo001/home-panel#43]
## Description
Currently, there is no way to easily control the manual alarm component. It would be awesome if we could have an alarm tile with an optional pin pad to disarm the system.

**Comment by timmo001** [comment]
Since I don't have an alarm, I'll need a little help with this one.

I've added the demo `alarm_control_panel.alarm` to my hass instance and have this:

![image](https://user-images.githubusercontent.com/28114703/44792805-a36ede00-ab9c-11e8-8fab-f8812a30a9dd.png)

@TheCellMC or anyone else who knows this platform, is this the whole of the alarm platform or can there be other options shown? 

I can make a UI in a dialog like the screenshot above, however am not sure if there are any other features for setting alarms etc. I am also looking how this entity would get set also

**Comment by TheCellMC** [comment]
> is this the whole of the alarm platform or can there be other options shown?
Yes, this is the whole of the alarm platform.

> I am also looking how this entity would get set also
Basically, the user specifies the password of the alarm in the config.
When the user disarms the alarm, he has to enter the code. If it matches the code in the config, it will disarm the alarm via `alarm_control_panel.alarm_disarm` and send over the code specified in the config.
To arm away, it sends `alarm_control_panel.alarm_arm_away`.
To arm home, it sends `alarm_control_panel.alarm_arm_home`.

The alarm panel has the following states:
`disarmed`
`armed_home`
`armed_away`
`pending` -> when the alarm is pending either because it is arming or because it is waiting before triggering the system
`triggered` -> when the alarm is triggered

However it would also be nice if the `warning` state could be implemented as it is used by [this popular project](https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386)

If you have any more question or if you need clarification on any points made, don't hesitate to ask. I'll do my best to reply as quickly as possible.

**Comment by timmo001** [comment]
Thanks for the super detailed reply @TheCellMC!

I will likely throw this up in a dialogue since the cards are pretty small for mobile devices

**Comment by timmo001** [comment]
Done!
