### ISSUE TITLE
Add opacity to background color

### ISSUE THREAD

**Issue by thundergreen** [timmo001/home-panel#611]
# Description

For the moment we can only use opacity 100% if background color is set to ```transparent```

Would be nice having a way to set opacity as an additional option for background color (maybe as a slider underneath the color?)

## Suggested Actions

adding slider underneath background color

**Comment by timmo001** [comment]
Since the background is just css, you can already do this. Opacity isn't the correct term for this. The `opacity` property would affect the whole element (foreground).

I will add an alpha slider to the color wheel however since this is supported in the library.

You can actually drastically change the look of the app by using the alpha channel

![image](https://user-images.githubusercontent.com/28114703/66351501-94d52780-e955-11e9-92fc-2501f6785a0b.png)

**Comment by thundergreen** [comment]
THIS! is exaclty what I was looking for. Great Thanks!
