### ISSUE TITLE
HA Camera entity

### ISSUE THREAD

**Issue by aptonline** [timmo001/home-panel#66]
Add the ability to show Home Assistant Camera entities as well as URLs.

Could the still url be created form the HA camera entity?

**Comment by timmo001** [comment]
You can use the `proxy_url` / `entity_picture` from Home Assitant for this

**Comment by aptonline** [comment]
https://www.home-assistant.io/components/camera.proxy/ ?

**Comment by timmo001** [comment]
Yes and if you go to the states section of hass, and click on the camera there is a link to the camera url I believe.

![image](https://user-images.githubusercontent.com/28114703/44925833-685cde00-ad47-11e8-9f57-35768a5585e8.png)

Personally, I use Shinobi for my cameras since it provides an mjpeg camera and a jpg screenshot that updates when you load the image. This is what I based the camera support on

**Comment by aptonline** [comment]
Intersting. I use Synology Surveillance Station currently, I'll download the docker and give it a whirl.

**Comment by aptonline** [comment]
Having great issues setting Shinobi up in docker on my Synology so had a play with Motioneye.

They allow still and video to be streamed but the URL they produce doesn't seem to work.

`http://***.***.***.***:****/picture/1/current/?_username=admin&_signature=92404ad8d7285d805c4b25768d00cae4240d4533`

Any chance of adding this method? don't really want to preprocess though HA if I can help it.

**Comment by timmo001** [comment]
The camera should be in an image format like `mjpeg`. Adding support for other formats would mean having to process images, which hass can already do with the proxy camera.

This issue is out of the scope of this project. I am only looking to extend the functionality of hass at this time.

I am closing this issue but will open up another to add iframe support, which would allow you to show any webpage you like, so long as your browser can see it.
